version: '3'
services:
  back:
    image: mathmau92/my-back-app
    ports:
      - "8080:5000"
    environment:
      - CURRENT_ENVIRONMENT=production
    # volumes:
    #   - ./data:/app/logs
  
  front:
    image: mathmau92/my-front-app
    ports:
      - "80:80"
    environment:
      - WS_BACK_URL=http://localhost:8080